apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-alpine
    tag: alpine
  name: nginx-alpine
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    targetPort: {{ .Values.service.port }} 
  selector:
    app: nginx-alpine
    tag: alpine
  type: {{ .Values.service.type }} 
status:
  loadBalancer: {}