apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values_prod.yaml
    # path to the folder with the YAML manifests
    path: exercises/helm
    repoURL: https://github.com/ayotomiwasalau/cloud-tooling 
    targetRevision: HEAD