apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-alpine
    tag: alpine
  name: nginx-alpine
  namespace: testbox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-alpine
      tag: alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-alpine
        tag: alpine
    spec:
      containers:
      - image: nginx:alpine
        name: nginx-alpine
        imagePullPolicy: IfNotPresent
status: {}